### ISSUE TITLE
No DOCTYPE in the HTML

### ISSUE THREAD

**Issue by jeena** [CampDev/Tasky#10]
You should use a <!DOCTYPE html> in the HTML otherwies browsers will hink you're using a very old HTML version which leads to all kinds of problems, especially in IE with their old box-model.

**Comment by Nygu** [comment]
I think I've fixed this (by adding <!DOCTYPE html> in every file that contains an html tag).

**Comment by jeena** [comment]
Btw. it would be cool if you could reference the commits with the issues like the Tent guys do. You even can close a issue with help of the message while committing, just add to the message `fixed #10` for example. Then github will reference it here on this page and close the issue automatically :)
