### ISSUE TITLE
Getting started with Tasky

### ISSUE THREAD

**Issue by ghost** [CampDev/Tasky#17]
When the user logs in to Tasky for the first time AND doesn't have any tasks or lists, automatically post a list called "Get started with Tasky", containing a couple of tasks, such as:
- Click the checkbox behind this task to mark this task finished.
- Click the X behind this task to delete this task.
- Click the list icon in the header to manage your lists.
- Click the post icon in the header to add a new task to a list.
- Delete the "Getting started" list and its tasks and create your own. :)

**Comment by Nygu** [comment]
I've decided to add a welcome message for users without tasks that tells them to create a list and add tasks. Should be sufficient.
