### ISSUE TITLE
Get rid of the table that contains the tasks

### ISSUE THREAD

**Issue by Nygu** [CampDev/Tasky#20]
We need to order things in such a way that we can keep the mobile interface clean while providing a more complete overview on the desktop. This probably means divs with a display:none; style on small screen sizes.

On mobile, I prefer to display the checkbox first (easy on your thumb), followed by the title and note. Upon clicking the text of the task, a detail view should appear that allows you to delete a task or edit it.

On the desktop, we should probably go back to: priority, title + note, date, check, delete.

**Comment by Cacauu** [comment]
I agree. The table was just a first solution as it didn't have a better idea and no time to style divs. 
The best might be to have a div .single_task around every task and then .check, .title, .note, .due etc. in .single_task
