### ISSUE TITLE
Priorities: front-end or back-end?

### ISSUE THREAD

**Issue by Nygu** [CampDev/Tasky#21]
I've been playing around with the way the priority of a post is presented and am having some difficulties presenting them in a way that makes sense.

Priorities are currently presented as a colored stripe. First of all, priorities should probably be on the left side of the post, since you are reading from left to right and the priority would determine whether you'd read something or not. However, putting the coloured stripes on the left doesn't look very well within the desktop interface (collides with the neutral sidebar) and on the mobile interface it looks out of balance (priority -> check -> title + note). Putting priorities on the far right, in my opinion, also defeats the purpose of displaying them. Especially on mobile, where popover scrollbars hide the priorities while scrolling.

Maybe I should just move away from the colored stripe idea and add priority icons to the design. But while trying to place them in a way that makes sense, it actually occurred to me that perhaps it doesn't even make sense at all to display the priority to the user within the task list. Perhaps, the app should handle priorities in such a way that the user doesn't need to have a visible priority indicator, essentially turning it into some sort of back-end info to present more useful task lists.

I'd be more than happy to hear what other people think of this little dilemma. :)

**Comment by poweruser82** [comment]
Color coding the priority could be problematic for color-blind people.

**Comment by mplorentz** [comment]
The left sidebar sounds good, maybe you just need some colors that don't clash. Another idea that would be hard to pull off would be to make the background of the checkbox the priority indicator. The box is going to be empty most of the time anyway so it would be a clever use of space, but I think it would be hard to make it look good.

**Comment by mplorentz** [comment]
For the color-blind, you can always have a preference to use a separate color scheme that is color-blind safe.

**Comment by Nygu** [comment]
I've decided to color-code the check boxes. Additionally, I will add tool tips to the check boxes to help indicate the priority. It's a pretty clever way to save space, while unobtrusively adding extra information to the items. :)
