### ISSUE TITLE
Cannot login from iOS 5 on 2nd Gen iPod Touch

### ISSUE THREAD

**Issue by Nygu** [CampDev/Tasky#25]
For some reason the "Loading, please wait" button gets stuck. Works on the iPad though (iOS 6).

**Comment by Cacauu** [comment]
Works perfectly well for my iPhone 4S, iOS 7. Where do you get stuck exactly? Do you have a screenshot?

**Comment by Nygu** [comment]
Apparently has something to do with Cupcake and webkit. Closing this now.
