### ISSUE TITLE
After creating a task in a list, redirect to that specific list

### ISSUE THREAD

**Issue by Nygu** [CampDev/Tasky#28]
I'd like to only have my "School" tab open at school, but whenever I post a new task, the "All lists" view gets displayed, showing all my personal tasks as well.

**Comment by Cacauu** [comment]
If I'm not completely wrong, that should already work, at least on the desktop. I'll have a look at mobile later.

**Comment by Nygu** [comment]
Try it yourself. When you post a task while in a list, the sending process happens and then you're in "all lists". ;-)
