### ISSUE TITLE
Broken image in header

### ISSUE THREAD

**Issue by jeena** [CampDev/Tasky#3]
On the right of the header there is a broken image, I assume this is where my avatar will show up?

**Comment by CampDev** [comment]
Yep. Right now it's a placeholder. We should have taken it out of the code before releasing. Sorry about that. Yannik wanted to get it working before release but tent didn't co-operate so we've pushed it to a future release.

**Comment by CampDev** [comment]
I've edited it out. It'll come back in the future. ;-)
