### ISSUE TITLE
"Things you need to do today"

### ISSUE THREAD

**Issue by Nygu** [CampDev/Tasky#31]
In the far future, I'd like to have an alarm clock app, that upon unlocking shows me which tasks I have to do today. Likewise, it would be nice if a potential Tasky app first told me about my tasks for that day, before I click on a button that takes me to all my tasks.

**Comment by Cacauu** [comment]
Added a "Today View" in [this commit](https://github.com/CampDev/Tasky/commit/4f90edfeb99cbfcb7231784b372d7f32dea25d52)
