### ISSUE TITLE
Not all tasks are displayed

### ISSUE THREAD

**Issue by Nygu** [CampDev/Tasky#35]
Both on the "All tasks" view as well as particular lists, only a certain amount of tasks are displayed. I cannot see the first tasks I have created because of this.

**Comment by Cacauu** [comment]
I don't think that this is possible and, if so, it's a frontend and not a backend problem. The backend doesn't set a limitation on posts that are fetched and the server shouldn't limit it then. Could you just try to add `var_export($posts);` to index.php after line 73 and see if the output contains something in the pages array? If so, I'll have to have a look at that.

**Comment by Nygu** [comment]
I suppose the line has changed by now?

Aside from broken list filtering, this is the most annoying bug at this particular moment. There are tasks I cannot finish because I cannot see them. :p
