### ISSUE TITLE
Make log out link more obvious

### ISSUE THREAD

**Issue by jeena** [CampDev/Tasky#38]
I had to scan the whole page to find the log out link in the bottom of the page just looking like Developer Resources link.

I think the log out link is a important one which should be easy to find.

**Comment by Nygu** [comment]
I've placed this under a settings icon in the header. Hope it's easier to find it now. ;-)

**Comment by jeena** [comment]
Hm, still kind of unexpected. I was thinking more like in almost every other webapp which often show who you're logged in as in the top right and there is also a "log out" link directly accessible. Like in Basecamp for example:

![Basecamp](http://ubuntu.allmyapps.com/data/b/a/basecam-Project-Management-BasecampHQ/WEB/ads_on_basecamp1.png)

This helps especially on computers which are used by more then one person.
