### ISSUE TITLE
date input not showind calendar

### ISSUE THREAD

**Issue by jeena** [CampDev/Tasky#5]
I don't know if his is only a Firefox issue but when creating or editing a task the date input field doesn't show any calendar and not even a label which would indicate that this is a date field, or at least a placeholder which would show a date so I know in which format I have to put in the date.

**Comment by CampDev** [comment]
It's supposed to bring up a calendar. We'll have a look at that on other browsers. ;-)

Seems like you're putting us to work. :p

**Comment by jeena** [comment]
oh yeah :D

**Comment by jeena** [comment]
In the mean time please add a placeholder with the date format you're expecting otherwise I don't know what to put in there.

**Comment by Cacauu** [comment]
If you're using the latest versions of Chrome or Safari, the browser should set a placeholder for you. For me, it says `tt.mm.jjjj` in Chrome and Safari. What browser are you using?

I just tried to add a `placeholder` or a default `value` to the field but it didn't seem to work for me. I'm not sure if `<input type="date">` supports a value or placeholder or if this just doesn't work in Chrome.

**Comment by Cacauu** [comment]
I don't really see a way to change that now. If anyone can help me out with a way to add a placeholder to a date field, let me know and I'll reopen this issue but I'll close it for now.

**Comment by jeena** [comment]
You can just add placeholder="dd/mm/yyyy" so it will show up in Firefox, Safari, etc. and then because you use jQuery already anyway you can also use http://jqueryui.com/datepicker/ so all browsers will get a date picker. Those which implement it natively will just use the native one, all others will use the jQuery UI one.
