### ISSUE TITLE
Sidebar and sorting not linked

### ISSUE THREAD

**Issue by jeena** [CampDev/Tasky#8]
I assume that is just not implemented yet?

**Comment by Nygu** [comment]
HA! We fixed this. :D

**Comment by jeena** [comment]
Nice, but why no reference to a commit?!!!!

**Comment by Cacauu** [comment]
Oops...
Here are the important commits:
[Due Tomorrow](https://github.com/CampDev/Tasky/commit/7cc7e42940df955eae844ec8406e5b19f1770db9)
[Due Today](https://github.com/CampDev/Tasky/commit/4f90edfeb99cbfcb7231784b372d7f32dea25d52)
[Upcoming](https://github.com/CampDev/Tasky/commit/9b6865f3108a7c6e9fdf57078a55f6ae45261231)
[Done/To Do filter](https://github.com/CampDev/Tasky/commit/3902b9c0deadc31f0ce8b65a5a87f3e4c1c8211a)

**Comment by Nygu** [comment]
7cc7e42 Enjoy :)

**Comment by jeena** [comment]
Thanks ;)
