### ISSUE TITLE
Developer resources style.css

### ISSUE THREAD

**Issue by jeena** [CampDev/Tasky#9]
There is no such file http://dev.campnews.org/tasky/style.css which is referenced in http://dev.campnews.org/tasky/developer.php therefore this page is without a stylesheet.

**Comment by CampDev** [comment]
Fixed the reference to css/style.css and putten a container around the text.

**Comment by Cacauu** [comment]
Finally fixed in [this commit](https://github.com/CampDev/Tasky/commit/769e4d0add68b1bdb47b132d3c78cd2f6cf1bc48), there was a typo before. Also updated the developer resources with information about the usage of fragments.
